
export interface FormSelections {
    type: string;
    subtype: string;
    mL: number;
    g: number;
}

export interface IDBEntry {
    cal_per_unit: number;
    protein_per_unit: number;
    calcium_per_unit: number;
    phos_per_unit: number;
    kalium_per_unit: number;
    natrium_per_unit: number;
    magnesium_per_unit: number;
    retinol_per_unit: number;
    vit_d_per_unit: number;
    carb_per_unit: number;
    fat_per_unit: number;
    displacement: number;
}

export const DEFAULT_FORM_SELECTIONS = {
    type: '',
    subtype: '',
    mL: 0,
    g: 0,
};

export const formulaTypes = [
    { label: 'Choose...', value: '', disabled: true },
    { label: 'Milk', value: 'f1' },
    { label: 'Liquid Pediatric', value: 'f2' },
    { label: 'Powder', value: 'f3' },
    { label: 'Additives (post-decant)', value: 'f4' },
];


export const formulaSubtypes = [
    [
        { label: 'MBM (USDA)', value: 'mbm_usda' },
        { label: 'MBM 22 with HMF', value: 'mbm_22_with_hmf' },
        { label: 'MBM 24 with HMF', value: 'mbm_24_with_hmf' },
        { label: 'MBM 26 with HMF', value: 'mbm_26_with_hmf' },
        { label: 'Similac PM 60/40 (20 cal/oz)', value: 'similac_pm_60/40_20_cal/oz' },
        { label: 'Pedialyte', value: 'pedialyte' },
        { label: 'Whole Milk (USDA data)', value: 'whole_milk_usda_data' },
        { label: 'BKE 1.0', value: 'bke_1.0' },
        { label: 'BKE 1.5', value: 'bke_1.5' },
        { label: 'BKE 1.5 (fiber)', value: 'bke_1.5_fiber' },
        { label: 'Nutren Jr 1.0 (50% whey)', value: 'nutren_jr_1.0_50%_whey' },
        { label: 'Nutren Jr fiber (50% whey)', value: 'nutren_jr_fiber_50%_whey' },
        { label: 'Pediasure 1.0', value: 'pediasure_1.0' },
        { label: 'Pediasure 1.5', value: 'pediasure_1.5' },
        { label: 'Pediasure 1.5 with fiber', value: 'pediasure_1.5_with_fiber' },
        { label: 'Compleat ped original 1.0', value: 'compleat_ped_original_1.0' },
        { label: 'Compleat ped original red calorie 0.6', value: 'compleat_ped_original_red_calorie_0.6' },
        { label: 'Compleat ped std 1.0 (pea)', value: 'compleat_ped_std_1.0_pea' },
        { label: 'Compleat ped std 1.4 (pea)', value: 'compleat_ped_std_1.4_pea' },
        { label: 'KF Pediatric Standard 1.2 (vanilla)', value: 'kf_pediatric_standard_1.2_vanilla' },
        { label: 'Peptamen Jr 1.0', value: 'peptamen_jr_1.0' },
        { label: 'Peptamen Jr 1.5', value: 'peptamen_jr_1.5' },
        { label: 'Pediasure peptide 1.0', value: 'pediasure_peptide_1.0' },
        { label: 'Pediasure peptide 1.5', value: 'pediasure_peptide_1.5' },
        { label: 'Compleat ped peptide 1.0 (pea)', value: 'compleat_ped_peptide_1.0_pea' },
        { label: 'Compleat ped peptide 1.5(pea)', value: 'compleat_ped_peptide_1.5pea' },
        { label: 'KF Pediatric Peptide 1.0', value: 'kf_pediatric_peptide_1.0' },
        { label: 'KF Pediatric Peptide 1.5', value: 'kf_pediatric_peptide_1.5' },
        { label: 'Vivonex RTF', value: 'vivonex_rtf' },
        { label: 'Neocate Splash', value: 'neocate_splash' },
        { label: 'KF Renal Support 1.8', value: 'kf_renal_support_1.8' },
        { label: 'Nepro', value: 'nepro' },
        { label: 'Renalcal', value: 'renalcal' },
        { label: 'Renastep', value: 'renastep' },
        { label: 'Suplena', value: 'suplena' },
        { label: 'Similac 360 Total Care', value: 'similac_360_total_care' },
        { label: 'Similac Pro Advance', value: 'similac_pro_advance' },
        { label: 'Enafmil NeuroPro', value: 'enafmil_neuro_pro' },
        { label: 'Gerber Good Start gentle', value: 'gerber_good_start_gentle' },
        { label: 'Total Comfort (pro Total Comfort)', value: 'total_comfort_pro_total_comfort' },
        { label: 'Enfamil Gentlease', value: 'enfamil_gentlease' },
        { label: 'Alimentum', value: 'alimentum' },
        { label: 'Nutramigen', value: 'nutramigen' },
        { label: 'Pregestimil', value: 'pregestimil' },
        { label: 'Gerber Extensive HA', value: 'gerber_extensive_ha' },
        { label: 'Pepticate', value: 'pepticate' },
        { label: 'Puramino Infant', value: 'puramino_infant' },
        { label: 'Neocate Infant', value: 'neocate_infant' },
        { label: 'Alfamino Infant', value: 'alfamino_infant' },
        { label: 'Elecare Infant', value: 'elecare_infant' },
        { label: 'Neocate Jr prebio, no flavor', value: 'neocate_jr_prebio,_no_flavor' },
        { label: 'Elecare Jr', value: 'elecare_jr' },
        { label: 'Essential care Jr', value: 'essential_care_jr' },
        { label: 'Vivonex TEN (80.4 g/pack)', value: 'vivonex_ten_80.4_g/pack' },
        { label: 'Neosure', value: 'neosure' },
        { label: 'Enfacare', value: 'enfacare' },
        { label: 'Renastart', value: 'renastart' },
        { label: 'Similac PM 60/40', value: 'similac_pm_60/40' },
        { label: 'Calcilo XD', value: 'calcilo_xd' },
        { label: 'Beneprotein', value: 'beneprotein' },
        { label: 'Complete Amino Acid', value: 'complete_amino_acid' },
        { label: 'Duocal', value: 'duocal' },
        { label: 'MCT Oil (Nestle) (946 mL/bottle)', value: 'mct_oil_nestle_946_m_l/bottle' },
        { label: 'PhosphaNeutral 250 (per tablet)', value: 'phospha_neutral_250_per_tablet' },
        { label: 'PhosNaK (per packet)', value: 'phos_na_k_per_packet' },
        { label: 'NaCl (per tablet)', value: 'na_cl_per_tablet' },
    ],
    [
        { label: 'MBM (USDA)', value: 'mbm_usda' },
        { label: 'MBM 22 with HMF', value: 'mbm_22_with_hmf' },
        { label: 'MBM 24 with HMF', value: 'mbm_24_with_hmf' },
        { label: 'MBM 26 with HMF', value: 'mbm_26_with_hmf' },
        { label: 'Similac PM 60/40 (20 cal/oz)', value: 'similac_pm_60/40_20_cal/oz' },
        { label: 'Pedialyte', value: 'pedialyte' },
        { label: 'Whole Milk (USDA data)', value: 'whole_milk_usda_data' },
    ],
    [
        { label: 'BKE 1.0', value: 'bke_1.0' },
        { label: 'BKE 1.5', value: 'bke_1.5' },
        { label: 'BKE 1.5 (fiber)', value: 'bke_1.5_fiber' },
        { label: 'Nutren Jr 1.0 (50% whey)', value: 'nutren_jr_1.0_50%_whey' },
        { label: 'Nutren Jr fiber (50% whey)', value: 'nutren_jr_fiber_50%_whey' },
        { label: 'Pediasure 1.0', value: 'pediasure_1.0' },
        { label: 'Pediasure 1.5', value: 'pediasure_1.5' },
        { label: 'Pediasure 1.5 with fiber', value: 'pediasure_1.5_with_fiber' },
        { label: 'Compleat ped original 1.0', value: 'compleat_ped_original_1.0' },
        { label: 'Compleat ped original red calorie 0.6', value: 'compleat_ped_original_red_calorie_0.6' },
        { label: 'Compleat ped std 1.0 (pea)', value: 'compleat_ped_std_1.0_pea' },
        { label: 'Compleat ped std 1.4 (pea)', value: 'compleat_ped_std_1.4_pea' },
        { label: 'KF Pediatric Standard 1.2 (vanilla)', value: 'kf_pediatric_standard_1.2_vanilla' },
        { label: 'Peptamen Jr 1.0', value: 'peptamen_jr_1.0' },
        { label: 'Peptamen Jr 1.5', value: 'peptamen_jr_1.5' },
        { label: 'Pediasure peptide 1.0', value: 'pediasure_peptide_1.0' },
        { label: 'Pediasure peptide 1.5', value: 'pediasure_peptide_1.5' },
        { label: 'Compleat ped peptide 1.0 (pea)', value: 'compleat_ped_peptide_1.0_pea' },
        { label: 'Compleat ped peptide 1.5(pea)', value: 'compleat_ped_peptide_1.5pea' },
        { label: 'KF Pediatric Peptide 1.0', value: 'kf_pediatric_peptide_1.0' },
        { label: 'KF Pediatric Peptide 1.5', value: 'kf_pediatric_peptide_1.5' },
        { label: 'Vivonex RTF', value: 'vivonex_rtf' },
        { label: 'Neocate Splash', value: 'neocate_splash' },
        { label: 'KF Renal Support 1.8', value: 'kf_renal_support_1.8' },
        { label: 'Nepro', value: 'nepro' },
        { label: 'Renalcal', value: 'renalcal' },
        { label: 'Renastep', value: 'renastep' },
        { label: 'Suplena', value: 'suplena' },
    ],
    [
        { label: 'Similac 360 Total Care', value: 'similac_360_total_care' },
        { label: 'Similac Pro Advance', value: 'similac_pro_advance' },
        { label: 'Enafmil NeuroPro', value: 'enafmil_neuro_pro' },
        { label: 'Gerber Good Start gentle', value: 'gerber_good_start_gentle' },
        { label: 'Total Comfort (pro Total Comfort)', value: 'total_comfort_pro_total_comfort' },
        { label: 'Enfamil Gentlease', value: 'enfamil_gentlease' },
        { label: 'Alimentum', value: 'alimentum' },
        { label: 'Nutramigen', value: 'nutramigen' },
        { label: 'Pregestimil', value: 'pregestimil' },
        { label: 'Gerber Extensive HA', value: 'gerber_extensive_ha' },
        { label: 'Pepticate', value: 'pepticate' },
        { label: 'Puramino Infant', value: 'puramino_infant' },
        { label: 'Neocate Infant', value: 'neocate_infant' },
        { label: 'Alfamino Infant', value: 'alfamino_infant' },
        { label: 'Elecare Infant', value: 'elecare_infant' },
        { label: 'Neocate Jr prebio, no flavor', value: 'neocate_jr_prebio,_no_flavor' },
        { label: 'Elecare Jr', value: 'elecare_jr' },
        { label: 'Essential care Jr', value: 'essential_care_jr' },
        { label: 'Vivonex TEN (80.4 g/pack)', value: 'vivonex_ten_80.4_g/pack' },
        { label: 'Neosure', value: 'neosure' },
        { label: 'Enfacare', value: 'enfacare' },
        { label: 'Renastart', value: 'renastart' },
        { label: 'Similac PM 60/40', value: 'similac_pm_60/40' },
        { label: 'Calcilo XD', value: 'calcilo_xd' },
    ],
    [
        { label: 'Beneprotein', value: 'beneprotein' },
        { label: 'Complete Amino Acid', value: 'complete_amino_acid' },
        { label: 'Duocal', value: 'duocal' },
        { label: 'MCT Oil (Nestle) (946 mL/bottle)', value: 'mct_oil_nestle_946_m_l/bottle' },
        { label: 'PhosphaNeutral 250 (per tablet)', value: 'phospha_neutral_250_per_tablet' },
        { label: 'PhosNaK (per packet)', value: 'phos_na_k_per_packet' },
        { label: 'NaCl (per tablet)', value: 'na_cl_per_tablet' },
    ],
];

export const db_at_home: { [key: string]: IDBEntry } = {

    'mbm_usda': {
        cal_per_unit: 0.67,
        protein_per_unit: 0.013,
        calcium_per_unit: 0.32,
        phos_per_unit: 0.14,
        kalium_per_unit: 0.48,
        natrium_per_unit: 0.17,
        magnesium_per_unit: 0.03,
        retinol_per_unit: 2.0,
        vit_d_per_unit: 0.04,
        carb_per_unit: 0.0689,
        fat_per_unit: 0.0438,
        displacement: NaN,
    },
    'mbm_22_with_hmf': {
        cal_per_unit: 0.75,
        protein_per_unit: 0.022,
        calcium_per_unit: 0.75,
        phos_per_unit: 0.42,
        kalium_per_unit: 0.66,
        natrium_per_unit: 0.38,
        magnesium_per_unit: 0.038,
        retinol_per_unit: 1.71,
        vit_d_per_unit: 0.93,
        carb_per_unit: 0.071,
        fat_per_unit: 0.042,
        displacement: NaN,
    },
    'mbm_24_with_hmf': {
        cal_per_unit: 0.81,
        protein_per_unit: 0.028,
        calcium_per_unit: 1.18,
        phos_per_unit: 0.65,
        kalium_per_unit: 0.79,
        natrium_per_unit: 0.46,
        magnesium_per_unit: 0.043,
        retinol_per_unit: 3.03,
        vit_d_per_unit: 1.67,
        carb_per_unit: 0.07,
        fat_per_unit: 0.048,
        displacement: NaN,
    },
    'mbm_26_with_hmf': {
        cal_per_unit: 0.88,
        protein_per_unit: 0.033,
        calcium_per_unit: 1.64,
        phos_per_unit: 0.9,
        kalium_per_unit: 0.94,
        natrium_per_unit: 0.55,
        magnesium_per_unit: 0.048,
        retinol_per_unit: 4.47,
        vit_d_per_unit: 2.4,
        carb_per_unit: 0.069,
        fat_per_unit: 0.055,
        displacement: NaN,
    },
    'similac_pm_60/40_20_cal/oz': {
        cal_per_unit: 0.666,
        protein_per_unit: 0.015,
        calcium_per_unit: 0.379,
        phos_per_unit: 0.189,
        kalium_per_unit: 0.541,
        natrium_per_unit: 0.162,
        magnesium_per_unit: 0.04,
        retinol_per_unit: 2.03,
        vit_d_per_unit: 0.41,
        carb_per_unit: 0.069,
        fat_per_unit: 0.0379,
        displacement: 0.79,
    },
    'pedialyte': {
        cal_per_unit: 0.1,
        protein_per_unit: NaN,
        calcium_per_unit: NaN,
        phos_per_unit: NaN,
        kalium_per_unit: 0.78,
        natrium_per_unit: 1.035,
        magnesium_per_unit: NaN,
        retinol_per_unit: 0.0,
        vit_d_per_unit: NaN,
        carb_per_unit: NaN,
        fat_per_unit: NaN,
        displacement: NaN,
    },
    'whole_milk_usda_data': {
        cal_per_unit: 0.62,
        protein_per_unit: 0.033233,
        calcium_per_unit: 1.25,
        phos_per_unit: 1.027,
        kalium_per_unit: 1.52666,
        natrium_per_unit: 0.38666,
        magnesium_per_unit: 0.122,
        retinol_per_unit: 1.05111,
        vit_d_per_unit: 0.45,
        carb_per_unit: 0.047,
        fat_per_unit: 0.0325333,
        displacement: NaN,
    },
    'bke_1.0': {
        cal_per_unit: 1.0,
        protein_per_unit: 0.03,
        calcium_per_unit: 1.37,
        phos_per_unit: 0.95,
        kalium_per_unit: 1.48,
        natrium_per_unit: 0.63,
        magnesium_per_unit: 0.17,
        retinol_per_unit: 1.4,
        vit_d_per_unit: 0.84,
        carb_per_unit: 0.14,
        fat_per_unit: 0.04,
        displacement: NaN,
    },
    'bke_1.5': {
        cal_per_unit: 1.5189873,
        protein_per_unit: 0.042194,
        calcium_per_unit: 1.6877637,
        phos_per_unit: 1.3502109,
        kalium_per_unit: 1.9831223,
        natrium_per_unit: 0.7694936,
        magnesium_per_unit: 0.2742616,
        retinol_per_unit: 2.250351333,
        vit_d_per_unit: 0.8438818,
        carb_per_unit: 0.1645569,
        fat_per_unit: 0.0759493,
        displacement: NaN,
    },
    'bke_1.5_fiber': {
        cal_per_unit: 1.5,
        protein_per_unit: 0.04,
        calcium_per_unit: 1.69,
        phos_per_unit: 1.35,
        kalium_per_unit: 1.98,
        natrium_per_unit: 0.76,
        magnesium_per_unit: 0.27,
        retinol_per_unit: 2.266666667,
        vit_d_per_unit: 0.84,
        carb_per_unit: 0.17,
        fat_per_unit: 0.08,
        displacement: NaN,
    },
    'nutren_jr_1.0_50%_whey': {
        cal_per_unit: 1.0,
        protein_per_unit: 0.03,
        calcium_per_unit: 1.2,
        phos_per_unit: 0.9,
        kalium_per_unit: 1.5,
        natrium_per_unit: 0.48,
        magnesium_per_unit: 0.2,
        retinol_per_unit: 1.6,
        vit_d_per_unit: 0.608,
        carb_per_unit: 0.112,
        fat_per_unit: 0.048,
        displacement: NaN,
    },
    'nutren_jr_fiber_50%_whey': {
        cal_per_unit: 1.0,
        protein_per_unit: 0.03,
        calcium_per_unit: 1.2,
        phos_per_unit: 0.9,
        kalium_per_unit: 1.5,
        natrium_per_unit: 0.48,
        magnesium_per_unit: 0.2,
        retinol_per_unit: 1.6,
        vit_d_per_unit: 0.608,
        carb_per_unit: 0.116,
        fat_per_unit: 0.048,
        displacement: NaN,
    },
    'pediasure_1.0': {
        cal_per_unit: 1.0,
        protein_per_unit: 0.028,
        calcium_per_unit: 1.39,
        phos_per_unit: 1.05,
        kalium_per_unit: 1.98,
        natrium_per_unit: 0.379,
        magnesium_per_unit: 0.17,
        retinol_per_unit: 1.966666667,
        vit_d_per_unit: 1.01,
        carb_per_unit: 0.139,
        fat_per_unit: 0.037,
        displacement: NaN,
    },
    'pediasure_1.5': {
        cal_per_unit: 1.4767932,
        protein_per_unit: 0.059,
        calcium_per_unit: 1.392405,
        phos_per_unit: 1.0548523,
        kalium_per_unit: 1.9831223,
        natrium_per_unit: 0.3797468,
        magnesium_per_unit: 0.1687763,
        retinol_per_unit: 1.969057333,
        vit_d_per_unit: 1.0126582,
        carb_per_unit: 0.16,
        fat_per_unit: 0.0675105,
        displacement: NaN,
    },
    'pediasure_1.5_with_fiber': {
        cal_per_unit: 1.5,
        protein_per_unit: 0.056,
        calcium_per_unit: 1.39,
        phos_per_unit: 1.05,
        kalium_per_unit: 1.98,
        natrium_per_unit: 0.379,
        magnesium_per_unit: 0.17,
        retinol_per_unit: 1.966666667,
        vit_d_per_unit: 1.01,
        carb_per_unit: 0.156,
        fat_per_unit: 0.068,
        displacement: NaN,
    },
    'compleat_ped_original_1.0': {
        cal_per_unit: 1.0,
        protein_per_unit: 0.038,
        calcium_per_unit: 1.4,
        phos_per_unit: 1.08,
        kalium_per_unit: 1.68,
        natrium_per_unit: 0.76,
        magnesium_per_unit: 0.2,
        retinol_per_unit: 1.6,
        vit_d_per_unit: 0.608,
        carb_per_unit: 0.136,
        fat_per_unit: 0.038,
        displacement: NaN,
    },
    'compleat_ped_original_red_calorie_0.6': {
        cal_per_unit: 0.6,
        protein_per_unit: 0.03,
        calcium_per_unit: 1.36,
        phos_per_unit: 1.04,
        kalium_per_unit: 1.68,
        natrium_per_unit: 0.76,
        magnesium_per_unit: 0.16,
        retinol_per_unit: 1.6,
        vit_d_per_unit: 0.608,
        carb_per_unit: 0.088,
        fat_per_unit: 0.02,
        displacement: NaN,
    },
    'compleat_ped_std_1.0_pea': {
        cal_per_unit: 1.0,
        protein_per_unit: 0.032,
        calcium_per_unit: 1.4,
        phos_per_unit: 0.96,
        kalium_per_unit: 1.52,
        natrium_per_unit: 0.68,
        magnesium_per_unit: 0.18,
        retinol_per_unit: 1.6,
        vit_d_per_unit: 0.736,
        carb_per_unit: 0.128,
        fat_per_unit: 0.044,
        displacement: NaN,
    },
    'compleat_ped_std_1.4_pea': {
        cal_per_unit: 1.4,
        protein_per_unit: 0.044,
        calcium_per_unit: 1.8,
        phos_per_unit: 1.32,
        kalium_per_unit: 2.64,
        natrium_per_unit: 1.24,
        magnesium_per_unit: 0.28,
        retinol_per_unit: 2.26666,
        vit_d_per_unit: 1.04,
        carb_per_unit: 0.172,
        fat_per_unit: 0.064,
        displacement: NaN,
    },
    'kf_pediatric_standard_1.2_vanilla': {
        cal_per_unit: 1.2,
        protein_per_unit: 0.05,
        calcium_per_unit: 1.2,
        phos_per_unit: 0.9,
        kalium_per_unit: 1.6,
        natrium_per_unit: 0.64,
        magnesium_per_unit: 0.2,
        retinol_per_unit: 2.93333,
        vit_d_per_unit: 1.2,
        carb_per_unit: 0.14,
        fat_per_unit: 0.05,
        displacement: NaN,
    },
    'peptamen_jr_1.0': {
        cal_per_unit: 1.0,
        protein_per_unit: 0.03,
        calcium_per_unit: 1.2,
        phos_per_unit: 0.9,
        kalium_per_unit: 1.5,
        natrium_per_unit: 0.48,
        magnesium_per_unit: 0.21,
        retinol_per_unit: 1.6,
        vit_d_per_unit: 0.608,
        carb_per_unit: 0.136,
        fat_per_unit: 0.04,
        displacement: NaN,
    },
    'peptamen_jr_1.5': {
        cal_per_unit: 1.5,
        protein_per_unit: 0.045,
        calcium_per_unit: 1.8,
        phos_per_unit: 1.36,
        kalium_per_unit: 2.3,
        natrium_per_unit: 0.72,
        magnesium_per_unit: 0.3,
        retinol_per_unit: 2.4,
        vit_d_per_unit: 0.912,
        carb_per_unit: 0.184,
        fat_per_unit: 0.068,
        displacement: NaN,
    },
    'pediasure_peptide_1.0': {
        cal_per_unit: 1.0,
        protein_per_unit: 0.03,
        calcium_per_unit: 1.39,
        phos_per_unit: 1.055,
        kalium_per_unit: 1.98,
        natrium_per_unit: 0.717,
        magnesium_per_unit: 0.17,
        retinol_per_unit: 1.9,
        vit_d_per_unit: 1.0,
        carb_per_unit: 0.134,
        fat_per_unit: 0.041,
        displacement: NaN,
    },
    'pediasure_peptide_1.5': {
        cal_per_unit: 1.5,
        protein_per_unit: 0.045,
        calcium_per_unit: 2.09,
        phos_per_unit: 1.58,
        kalium_per_unit: 2.975,
        natrium_per_unit: 1.075,
        magnesium_per_unit: 0.255,
        retinol_per_unit: 2.833333333,
        vit_d_per_unit: 1.0,
        carb_per_unit: 0.201,
        fat_per_unit: 0.061,
        displacement: NaN,
    },
    'compleat_ped_peptide_1.0_pea': {
        cal_per_unit: 1.0,
        protein_per_unit: 0.038,
        calcium_per_unit: 1.2,
        phos_per_unit: 0.96,
        kalium_per_unit: 1.52,
        natrium_per_unit: 0.54,
        magnesium_per_unit: 0.18,
        retinol_per_unit: 1.533333333,
        vit_d_per_unit: 0.608,
        carb_per_unit: 0.132,
        fat_per_unit: 0.04,
        displacement: NaN,
    },
    'compleat_ped_peptide_1.5pea': {
        cal_per_unit: 1.5,
        protein_per_unit: 0.052,
        calcium_per_unit: 1.8,
        phos_per_unit: 1.4,
        kalium_per_unit: 2.56,
        natrium_per_unit: 1.12,
        magnesium_per_unit: 0.3,
        retinol_per_unit: 2.4,
        vit_d_per_unit: 0.8,
        carb_per_unit: 0.172,
        fat_per_unit: 0.072,
        displacement: NaN,
    },
    'kf_pediatric_peptide_1.0': {
        cal_per_unit: 1.0,
        protein_per_unit: 0.04,
        calcium_per_unit: 1.2,
        phos_per_unit: 0.9,
        kalium_per_unit: 1.5,
        natrium_per_unit: 0.64,
        magnesium_per_unit: 0.2,
        retinol_per_unit: 1.833333333,
        vit_d_per_unit: 1.2,
        carb_per_unit: 0.12,
        fat_per_unit: 0.04,
        displacement: NaN,
    },
    'kf_pediatric_peptide_1.5': {
        cal_per_unit: 1.5,
        protein_per_unit: 0.05,
        calcium_per_unit: 1.6,
        phos_per_unit: 1.2,
        kalium_per_unit: 1.92,
        natrium_per_unit: 0.8,
        magnesium_per_unit: 0.34,
        retinol_per_unit: 2.2,
        vit_d_per_unit: 1.2,
        carb_per_unit: 0.16,
        fat_per_unit: 0.07,
        displacement: NaN,
    },
    'vivonex_rtf': {
        cal_per_unit: 1.0,
        protein_per_unit: 0.05,
        calcium_per_unit: 0.67,
        phos_per_unit: 0.67,
        kalium_per_unit: 1.2,
        natrium_per_unit: 0.7,
        magnesium_per_unit: 0.27,
        retinol_per_unit: 3.3,
        vit_d_per_unit: 0.56,
        carb_per_unit: 0.176,
        fat_per_unit: 0.0115,
        displacement: NaN,
    },
    'neocate_splash': {
        cal_per_unit: 1.0,
        protein_per_unit: 0.03,
        calcium_per_unit: 1.18,
        phos_per_unit: 0.8,
        kalium_per_unit: 1.37,
        natrium_per_unit: 0.5,
        magnesium_per_unit: 0.16,
        retinol_per_unit: 2.0,
        vit_d_per_unit: 0.8,
        carb_per_unit: 0.105,
        fat_per_unit: 0.051,
        displacement: NaN,
    },
    'kf_renal_support_1.8': {
        cal_per_unit: 1.8,
        protein_per_unit: 0.08,
        calcium_per_unit: 1.2,
        phos_per_unit: 0.84,
        kalium_per_unit: 1.0,
        natrium_per_unit: 1.0,
        magnesium_per_unit: 0.16,
        retinol_per_unit: 3.86666,
        vit_d_per_unit: 1.2,
        carb_per_unit: 0.172,
        fat_per_unit: 0.088,
        displacement: NaN,
    },
    'nepro': {
        cal_per_unit: 1.77,
        protein_per_unit: 0.08,
        calcium_per_unit: 1.05,
        phos_per_unit: 0.72,
        kalium_per_unit: 0.95,
        natrium_per_unit: 1.05,
        magnesium_per_unit: 0.17,
        retinol_per_unit: 2.533333333,
        vit_d_per_unit: 0.64,
        carb_per_unit: 0.16,
        fat_per_unit: 0.097,
        displacement: NaN,
    },
    'renalcal': {
        cal_per_unit: 2.0,
        protein_per_unit: 0.03,
        calcium_per_unit: 0.06,
        phos_per_unit: 0.1,
        kalium_per_unit: 0.08,
        natrium_per_unit: 0.06,
        magnesium_per_unit: 0.02,
        retinol_per_unit: 0.0,
        vit_d_per_unit: 0.0,
        carb_per_unit: 0.292,
        fat_per_unit: 0.082,
        displacement: NaN,
    },
    'renastep': {
        cal_per_unit: 2.0,
        protein_per_unit: 0.04,
        calcium_per_unit: 0.47,
        phos_per_unit: 0.3,
        kalium_per_unit: 0.35,
        natrium_per_unit: 0.84,
        magnesium_per_unit: 0.15,
        retinol_per_unit: 1.3,
        vit_d_per_unit: 0.64,
        carb_per_unit: 0.21,
        fat_per_unit: 0.11,
        displacement: NaN,
    },
    'suplena': {
        cal_per_unit: 1.772,
        protein_per_unit: 0.045,
        calcium_per_unit: 1.055,
        phos_per_unit: 0.717,
        kalium_per_unit: 1.055,
        natrium_per_unit: 0.802,
        magnesium_per_unit: 0.169,
        retinol_per_unit: 3.163333333,
        vit_d_per_unit: 0.844,
        carb_per_unit: 0.194,
        fat_per_unit: 0.097,
        displacement: NaN,
    },
    'similac_360_total_care': {
        cal_per_unit: 5.17,
        protein_per_unit: 0.107,
        calcium_per_unit: 4.032599,
        phos_per_unit: 2.1714,
        kalium_per_unit: 5.4284999,
        natrium_per_unit: 1.2408,
        magnesium_per_unit: 0.3102,
        retinol_per_unit: 15.51,
        vit_d_per_unit: 3.101999,
        carb_per_unit: 0.55319,
        fat_per_unit: 0.28952,
        displacement: 0.77,
    },
    'similac_pro_advance': {
        cal_per_unit: 5.17,
        protein_per_unit: 0.107,
        calcium_per_unit: 4.032599,
        phos_per_unit: 2.1714,
        kalium_per_unit: 5.4284999,
        natrium_per_unit: 1.2408,
        magnesium_per_unit: 0.3102,
        retinol_per_unit: 15.51,
        vit_d_per_unit: 3.101999,
        carb_per_unit: 0.55319,
        fat_per_unit: 0.28952,
        displacement: 0.77,
    },
    'enafmil_neuro_pro': {
        cal_per_unit: 5.1,
        protein_per_unit: 0.107,
        calcium_per_unit: 4.0,
        phos_per_unit: 2.2,
        kalium_per_unit: 5.5,
        natrium_per_unit: 1.38,
        magnesium_per_unit: 0.41,
        retinol_per_unit: 15.3,
        vit_d_per_unit: 3.8,
        carb_per_unit: 0.58,
        fat_per_unit: 0.27,
        displacement: 0.77,
    },
    'gerber_good_start_gentle': {
        cal_per_unit: 5.12,
        protein_per_unit: 0.1075,
        calcium_per_unit: 3.4304,
        phos_per_unit: 1.9456,
        kalium_per_unit: 5.5296,
        natrium_per_unit: 1.3824,
        magnesium_per_unit: 0.3584,
        retinol_per_unit: 15.36,
        vit_d_per_unit: 3.328,
        carb_per_unit: 0.58368,
        fat_per_unit: 0.26112,
        displacement: 0.76,
    },
    'total_comfort_pro_total_comfort': {
        cal_per_unit: 5.06,
        protein_per_unit: 0.117,
        calcium_per_unit: 5.313,
        phos_per_unit: 3.795,
        kalium_per_unit: 5.9708,
        natrium_per_unit: 2.2264,
        magnesium_per_unit: 0.3036,
        retinol_per_unit: 15.36,
        vit_d_per_unit: 3.101999,
        carb_per_unit: 0.54142,
        fat_per_unit: 0.27324,
        displacement: 0.77,
    },
    'enfamil_gentlease': {
        cal_per_unit: 5.1,
        protein_per_unit: 0.12,
        calcium_per_unit: 4.2,
        phos_per_unit: 2.3,
        kalium_per_unit: 5.5,
        natrium_per_unit: 1.84,
        magnesium_per_unit: 0.41,
        retinol_per_unit: 15.3,
        vit_d_per_unit: 3.1,
        carb_per_unit: 0.55,
        fat_per_unit: 0.27,
        displacement: 0.77,
    },
    'alimentum': {
        cal_per_unit: 5.19,
        protein_per_unit: 0.1402,
        calcium_per_unit: 5.3445,
        phos_per_unit: 3.8175,
        kalium_per_unit: 6.0062,
        natrium_per_unit: 2.2396,
        magnesium_per_unit: 0.38175,
        retinol_per_unit: 15.27,
        vit_d_per_unit: 3.054,
        carb_per_unit: 0.51918,
        fat_per_unit: 0.281986,
        displacement: 0.76,
    },
    'nutramigen': {
        cal_per_unit: 5.0,
        protein_per_unit: 0.14,
        calcium_per_unit: 4.7,
        phos_per_unit: 2.6,
        kalium_per_unit: 5.5,
        natrium_per_unit: 2.35,
        magnesium_per_unit: 0.4,
        retinol_per_unit: 15.27,
        vit_d_per_unit: 3.0,
        carb_per_unit: 0.515,
        fat_per_unit: 0.265,
        displacement: 0.78,
    },
    'pregestimil': {
        cal_per_unit: 5.0,
        protein_per_unit: 0.14,
        calcium_per_unit: 4.7,
        phos_per_unit: 2.6,
        kalium_per_unit: 5.5,
        natrium_per_unit: 2.35,
        magnesium_per_unit: 0.4,
        retinol_per_unit: 17.5,
        vit_d_per_unit: 2.5,
        carb_per_unit: 0.52,
        fat_per_unit: 0.245,
        displacement: 0.78,
    },
    'gerber_extensive_ha': {
        cal_per_unit: 4.93,
        protein_per_unit: 0.1346,
        calcium_per_unit: 4.437,
        phos_per_unit: 3.1059001,
        kalium_per_unit: 4.8314001,
        natrium_per_unit: 1.8734,
        magnesium_per_unit: 0.4437,
        retinol_per_unit: 15.381771,
        vit_d_per_unit: 2.465,
        carb_per_unit: 0.53737,
        fat_per_unit: 0.25143,
        displacement: 0.72,
    },
    'pepticate': {
        cal_per_unit: 4.92,
        protein_per_unit: 0.117,
        calcium_per_unit: 3.46,
        phos_per_unit: 1.82,
        kalium_per_unit: 5.98,
        natrium_per_unit: 1.5,
        magnesium_per_unit: 0.39,
        retinol_per_unit: 12.933,
        vit_d_per_unit: 3.76,
        carb_per_unit: 0.517,
        fat_per_unit: 0.255,
        displacement: 0.74,
    },
    'puramino_infant': {
        cal_per_unit: 5.0,
        protein_per_unit: 0.14,
        calcium_per_unit: 5.8,
        phos_per_unit: 3.2,
        kalium_per_unit: 5.5,
        natrium_per_unit: 2.4,
        magnesium_per_unit: 0.4,
        retinol_per_unit: 15.0,
        vit_d_per_unit: 3.0,
        carb_per_unit: 0.53,
        fat_per_unit: 0.27,
        displacement: 0.77,
    },
    'neocate_infant': {
        cal_per_unit: 4.83,
        protein_per_unit: 0.135,
        calcium_per_unit: 5.61,
        phos_per_unit: 3.97,
        kalium_per_unit: 5.25,
        natrium_per_unit: 1.89,
        magnesium_per_unit: 5.1,
        retinol_per_unit: 13.53333333,
        vit_d_per_unit: 3.52,
        carb_per_unit: 0.52,
        fat_per_unit: 0.245,
        displacement: 0.7,
    },
    'alfamino_infant': {
        cal_per_unit: 4.94,
        protein_per_unit: 0.1277,
        calcium_per_unit: 5.8786,
        phos_per_unit: 3.8532,
        kalium_per_unit: 4.94,
        natrium_per_unit: 1.976,
        magnesium_per_unit: 0.4446,
        retinol_per_unit: 15.561,
        vit_d_per_unit: 2.815802,
        carb_per_unit: 0.5434,
        fat_per_unit: 0.246635,
        displacement: 0.72,
    },
    'elecare_infant': {
        cal_per_unit: 5.0,
        protein_per_unit: 0.14,
        calcium_per_unit: 6.0,
        phos_per_unit: 3.3,
        kalium_per_unit: 5.3,
        natrium_per_unit: 1.85,
        magnesium_per_unit: 0.4,
        retinol_per_unit: 23.0,
        vit_d_per_unit: 3.5,
        carb_per_unit: 0.52,
        fat_per_unit: 0.27,
        displacement: 0.78,
    },
    'neocate_jr_prebio,_no_flavor': {
        cal_per_unit: 4.72,
        protein_per_unit: 0.14632,
        calcium_per_unit: 5.664,
        phos_per_unit: 3.81848,
        kalium_per_unit: 6.5136,
        natrium_per_unit: 2.3883,
        magnesium_per_unit: 0.76464,
        retinol_per_unit: 9.5344,
        vit_d_per_unit: 3.7996,
        carb_per_unit: 0.5144809,
        fat_per_unit: 0.2312804,
        displacement: 0.74,
    },
    'elecare_jr': {
        cal_per_unit: 4.69,
        protein_per_unit: 0.1454,
        calcium_per_unit: 5.4300392,
        phos_per_unit: 3.9499603,
        kalium_per_unit: 7.0581259,
        natrium_per_unit: 2.122988,
        magnesium_per_unit: 0.7400394,
        retinol_per_unit: 12.807307,
        vit_d_per_unit: 2.8121497,
        carb_per_unit: 0.4935127,
        fat_per_unit: 0.2270995,
        displacement: 0.74,
    },
    'essential_care_jr': {
        cal_per_unit: 4.94,
        protein_per_unit: 0.193,
        calcium_per_unit: 5.882,
        phos_per_unit: 3.82,
        kalium_per_unit: 4.813,
        natrium_per_unit: 4.3,
        magnesium_per_unit: 0.811,
        retinol_per_unit: 9.662,
        vit_d_per_unit: 3.907,
        carb_per_unit: 0.452,
        fat_per_unit: 0.247,
        displacement: 0.773,
    },
    'vivonex_ten_80.4_g/pack': {
        cal_per_unit: 3.75,
        protein_per_unit: 0.12,
        calcium_per_unit: 2.1,
        phos_per_unit: 2.1,
        kalium_per_unit: 3.9495,
        natrium_per_unit: 2.584,
        magnesium_per_unit: 0.84,
        retinol_per_unit: 10.6442,
        vit_d_per_unit: 1.6807,
        carb_per_unit: 0.86555,
        fat_per_unit: 0.0104,
        displacement: 0.62,
    },
    'neosure': {
        cal_per_unit: 5.13,
        protein_per_unit: 0.1438,
        calcium_per_unit: 5.3865,
        phos_per_unit: 3.1806,
        kalium_per_unit: 7.2846,
        natrium_per_unit: 1.6929,
        magnesium_per_unit: 0.4617,
        retinol_per_unit: 17.955,
        vit_d_per_unit: 3.591,
        carb_per_unit: 0.51813,
        fat_per_unit: 0.28215,
        displacement: 0.76,
    },
    'enfacare': {
        cal_per_unit: 5.0,
        protein_per_unit: 0.139,
        calcium_per_unit: 6.0,
        phos_per_unit: 3.3,
        kalium_per_unit: 5.3,
        natrium_per_unit: 1.85,
        magnesium_per_unit: 0.4,
        retinol_per_unit: 23.0,
        vit_d_per_unit: 3.5,
        carb_per_unit: 0.52,
        fat_per_unit: 0.27,
        displacement: 0.78,
    },
    'renastart': {
        cal_per_unit: 4.94,
        protein_per_unit: 0.075,
        calcium_per_unit: 1.0,
        phos_per_unit: 0.83,
        kalium_per_unit: 0.95,
        natrium_per_unit: 2.1,
        magnesium_per_unit: 0.35,
        retinol_per_unit: 3.666666667,
        vit_d_per_unit: 3.92,
        carb_per_unit: 0.62,
        fat_per_unit: 0.24,
        displacement: 0.74,
    },
    'similac_pm_60/40': {
        cal_per_unit: 5.14,
        protein_per_unit: 0.1126,
        calcium_per_unit: 2.874,
        phos_per_unit: 1.4392,
        kalium_per_unit: 4.112,
        natrium_per_unit: 1.2336,
        magnesium_per_unit: 0.3084,
        retinol_per_unit: 15.42,
        vit_d_per_unit: 3.08,
        carb_per_unit: 0.52,
        fat_per_unit: 0.29,
        displacement: 0.79,
    },
    'calcilo_xd': {
        cal_per_unit: 5.13,
        protein_per_unit: 0.114,
        calcium_per_unit: 0.15,
        phos_per_unit: 1.28,
        kalium_per_unit: 4.2,
        natrium_per_unit: 1.25,
        magnesium_per_unit: 0.31,
        retinol_per_unit: 15.4,
        vit_d_per_unit: 0.0,
        carb_per_unit: 0.523,
        fat_per_unit: 0.287,
        displacement: NaN,
    },
    'beneprotein': {
        cal_per_unit: 3.57,
        protein_per_unit: 0.86,
        calcium_per_unit: NaN,
        phos_per_unit: NaN,
        kalium_per_unit: NaN,
        natrium_per_unit: 2.14,
        magnesium_per_unit: NaN,
        retinol_per_unit: NaN,
        vit_d_per_unit: NaN,
        carb_per_unit: NaN,
        fat_per_unit: NaN,
        displacement: 0.71,
    },
    'complete_amino_acid': {
        cal_per_unit: 3.28,
        protein_per_unit: 0.82,
        calcium_per_unit: NaN,
        phos_per_unit: NaN,
        kalium_per_unit: NaN,
        natrium_per_unit: NaN,
        magnesium_per_unit: NaN,
        retinol_per_unit: NaN,
        vit_d_per_unit: NaN,
        carb_per_unit: NaN,
        fat_per_unit: NaN,
        displacement: 0.75,
    },
    'duocal': {
        cal_per_unit: 4.92,
        protein_per_unit: 0.0,
        calcium_per_unit: NaN,
        phos_per_unit: NaN,
        kalium_per_unit: NaN,
        natrium_per_unit: NaN,
        magnesium_per_unit: NaN,
        retinol_per_unit: NaN,
        vit_d_per_unit: NaN,
        carb_per_unit: 0.727,
        fat_per_unit: 0.223,
        displacement: 0.77,
    },
    'mct_oil_nestle_946_m_l/bottle': {
        cal_per_unit: 7.667,
        protein_per_unit: NaN,
        calcium_per_unit: NaN,
        phos_per_unit: NaN,
        kalium_per_unit: NaN,
        natrium_per_unit: NaN,
        magnesium_per_unit: NaN,
        retinol_per_unit: NaN,
        vit_d_per_unit: NaN,
        carb_per_unit: NaN,
        fat_per_unit: 0.933,
        displacement: NaN,
    },
    'phospha_neutral_250_per_tablet': {
        cal_per_unit: NaN,
        protein_per_unit: NaN,
        calcium_per_unit: NaN,
        phos_per_unit: 250.0,
        kalium_per_unit: 45.0,
        natrium_per_unit: 298.0,
        magnesium_per_unit: NaN,
        retinol_per_unit: NaN,
        vit_d_per_unit: NaN,
        carb_per_unit: NaN,
        fat_per_unit: NaN,
        displacement: NaN,
    },
    'phos_na_k_per_packet': {
        cal_per_unit: NaN,
        protein_per_unit: NaN,
        calcium_per_unit: NaN,
        phos_per_unit: 250.0,
        kalium_per_unit: 88.0,
        natrium_per_unit: 134.0,
        magnesium_per_unit: NaN,
        retinol_per_unit: NaN,
        vit_d_per_unit: NaN,
        carb_per_unit: NaN,
        fat_per_unit: NaN,
        displacement: NaN,
    },
    'na_cl_per_tablet': {
        cal_per_unit: NaN,
        protein_per_unit: NaN,
        calcium_per_unit: NaN,
        phos_per_unit: NaN,
        kalium_per_unit: NaN,
        natrium_per_unit: 394.0,
        magnesium_per_unit: NaN,
        retinol_per_unit: NaN,
        vit_d_per_unit: NaN,
        carb_per_unit: NaN,
        fat_per_unit: NaN,
        displacement: NaN,
    },
};
